#!/bin/bash

set -e

gunicorn \
      -w 1 \
      -k gthread \
      --threads 20 \
      --timeout 120 \
      -b  0.0.0.0:8088 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      "superset.app:create_app()"
